export default {
  DB_HOST: 'http://localhost:54321',
  // Automatically generated by supabase CLI for local env
  DB_ACCESS_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSJ9.vI9obAHOGyVVKa3pD--kJlyxp-Z2zV9UUMAhKpNLAcU ',
  CONFIG_IDENTIFIER: '00000000-0000-0000-0000-000000000000',
  SLACK_WEBHOOK_URL: 'https://slack-webhook-mock.com'
};
